<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260616091025 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA IF NOT EXISTS public');
        $this->addSql('CREATE TABLE game_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE library (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A18098BCA76ED395 ON library (user_id)');
        $this->addSql('CREATE TABLE set (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, library_id INT NOT NULL, game_type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E61425DCFE2541D7 ON set (library_id)');
        $this->addSql('CREATE INDEX IDX_E61425DC508EF3BC ON set (game_type_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pseudo VARCHAR(50) NOT NULL, mail VARCHAR(50) NOT NULL, api_token VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_MAIL ON "user" (mail)');
        $this->addSql('ALTER TABLE library ADD CONSTRAINT FK_A18098BCA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE set ADD CONSTRAINT FK_E61425DCFE2541D7 FOREIGN KEY (library_id) REFERENCES library (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE set ADD CONSTRAINT FK_E61425DC508EF3BC FOREIGN KEY (game_type_id) REFERENCES game_type (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE library DROP CONSTRAINT FK_A18098BCA76ED395');
        $this->addSql('ALTER TABLE set DROP CONSTRAINT FK_E61425DCFE2541D7');
        $this->addSql('ALTER TABLE set DROP CONSTRAINT FK_E61425DC508EF3BC');
        $this->addSql('DROP TABLE game_type');
        $this->addSql('DROP TABLE library');
        $this->addSql('DROP TABLE set');
        $this->addSql('DROP TABLE "user"');
    }
}
