<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260616082350 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE game_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE set ADD game_type_id INT NOT NULL');
        $this->addSql('ALTER TABLE set ADD CONSTRAINT FK_E61425DC508EF3BC FOREIGN KEY (game_type_id) REFERENCES game_type (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_E61425DC508EF3BC ON set (game_type_id)');
        $this->addSql('DROP INDEX uniq_identifier_email');
        $this->addSql('ALTER TABLE "user" ADD pseudo VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD mail VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD api_token VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" DROP email');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_MAIL ON "user" (mail)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE game_type');
        $this->addSql('ALTER TABLE set DROP CONSTRAINT FK_E61425DC508EF3BC');
        $this->addSql('DROP INDEX IDX_E61425DC508EF3BC');
        $this->addSql('ALTER TABLE set DROP game_type_id');
        $this->addSql('DROP INDEX UNIQ_IDENTIFIER_MAIL');
        $this->addSql('ALTER TABLE "user" ADD email VARCHAR(180) NOT NULL');
        $this->addSql('ALTER TABLE "user" DROP pseudo');
        $this->addSql('ALTER TABLE "user" DROP mail');
        $this->addSql('ALTER TABLE "user" DROP api_token');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (email)');
    }
}
