<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260616100038 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE card (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, extension VARCHAR(255) NOT NULL, numero VARCHAR(255) NOT NULL, game_type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_161498D3508EF3BC ON card (game_type_id)');
        $this->addSql('ALTER TABLE card ADD CONSTRAINT FK_161498D3508EF3BC FOREIGN KEY (game_type_id) REFERENCES game_type (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE card DROP CONSTRAINT FK_161498D3508EF3BC');
        $this->addSql('DROP TABLE card');
    }
}
